#!/usr/bin/env node
let Program = require('commander')
let Actions = require('./models/user')
let Errors = require('./libs/errors')

for (let action in Actions){
	Actions[action](Program).catch(Errors.errorFunc)
}

Program
.parse(process.argv)
